apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "event-system.fullname" . }}-worker
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "event-system.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      {{- include "event-system.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: worker
        {{- include "event-system.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.image.worker.repository }}:{{ .Values.image.worker.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          # Worker has no ports
          ports: []

          # Shared env
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              {{- if hasKey $val "valueFrom" }}
              valueFrom:
                secretKeyRef:
                  name: {{ $val.valueFrom.secretKeyRef.name }}
                  key: {{ $val.valueFrom.secretKeyRef.key }}
              {{- else }}
              value: "{{ $val }}"
              {{- end }}
            {{- end }}

          command:
            - "/app/.venv/bin/python"
            - "-u"
            - "-m"
            - "app.workers.consumer"

          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
